name: etisalatdemotv
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: 2.8.6
  shared_preferences: 2.2.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  file: ^7.0.1
  platform: ^3.1.6

  shared_preferences_android: 2.2.1
  shared_preferences_linux: 2.3.2
  shared_preferences_windows: 2.3.2
  video_player_android: 2.4.14

  video_player_avfoundation:
    git:
      url: https://github.com/DenisovAV/flutter-tvos-packages.git
      path: packages/video_player/video_player_avfoundation

  shared_preferences_foundation:
    git:
      url: https://github.com/DenisovAV/flutter-tvos-packages.git
      path: packages/shared_preferences/shared_preferences_foundation

  video_player_platform_interface:
    git:
      url: https://github.com/DenisovAV/flutter-tvos-packages.git
      path: packages/video_player/video_player_platform_interface

  shared_preferences_platform_interface:
    git:
      url: https://github.com/DenisovAV/flutter-tvos-packages.git
      path: packages/shared_preferences/shared_preferences_platform_interface

flutter:
  uses-material-design: true

  assets:
    - assets/video/
    - assets/images/